module.exports = {
  brew: [
    // http://conqueringthecommandline.com/book/ack_ag
    'ack',
    'ag',
    // https://github.com/wting/autojump
    'autojump',
    // alternative to `cat`: https://github.com/sharkdp/bat
    'bat',
    // Install GNU core utilities (those that come with macOS are outdated)
    // Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
    'coreutils',
    'dos2unix',
    // Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
    'findutils',
    // 'fortune',
    'fzf',
    'readline', // ensure gawk gets good readline
    'gawk',
    // http://www.lcdf.org/gifsicle/ (because I'm a gif junky)
    'gifsicle',
    'gnupg',
    // Install GNU `sed`, overwriting the built-in `sed`
    // so we can do "sed -i 's/foo/bar/' file" instead of "sed -i '' 's/foo/bar/' file"
    'gnu-sed --with-default-names',
    // upgrade grep so we can get things like inverted match (-v)
    'grep --with-default-names',
    // better, more recent grep
    'homebrew/dupes/grep',
    // https://github.com/jkbrzt/httpie
    'httpie',
    // jq is a sort of JSON grep
    'jq',
    // Mac App Store CLI: https://github.com/mas-cli/mas
    'mas',
    // Install some other useful utilities like `sponge`
    'moreutils',
    'nmap',
    'openconnect',
    'reattach-to-user-namespace',
    // better/more recent version of screen
    'homebrew/dupes/screen',
    'tmux',
    'todo-txt',
    'tree',
    'ttyrec',
    // better, more recent vim
    'vim --with-client-server --with-override-system-vi',
    'watch',
    // Install wget with IRI support
    'wget --enable-iri',
'deno',
'gnutls',
'libvterm',
'nettle',
'pkg-config',
'unbound',
'adns',
'diffutils',
'libidn',
'libyaml',
'nghttp2',
'unibilium',
'ansible',
'libidn2',
'libzip',
'node',
'python',
'unixodbc',
'apr',
'fontconfig',
'harfbuzz',
'libksba',
'links',
'npth',
'python@3.8',
'apr-util',
'freetds',
'htop',
'libmetalink',
'lnav',
'nspr',
'rbenv',
'argon2',
'freetype',
'lua',
'nss',
'webp',
'aspell',
'fribidi',
'irssi',
'ibpq',
'luajit',
'openldap',
'rtmpdump',
'autoconf',
'jansson',
'librsvg',
'lzo',
'openssl',
'xz',
'gdbm',
'jemalloc',
'libsodium',
'mcrypt',
'openssl@1.1',
'ruby-build',
'yarn',
'brotli',
'gdk-pixbuf',
'jpeg',
'libssh2',
'mhash',
'p11-kit',
'sass',
'z',
'c-ares',
'gettext',
'lagoon',
'libtasn1',
'mkcert',
'p7zip',
'speedtest-cli',
'zplug',
'cairo',
'libassuan',
'libtermkey',
'mpfr',
'pango',
'sqlite',
'git-flow-avh',
'libcroco',
'libtiff',
'msgpack',
'pcre',
'terminal-notifier',
'zsh-syntax-highlighting',
'composer',
'glib',
'libev',
'libtool',
'mutt',
'pcre2',
'tidy-html5',
'gmp',
'libevent',
'libunistring',
'namebench',
'perl',
'curl-openssl',
'gnu-getopt',
'libffi',
'libusb',
'ncurses',
'pinentry',
'libgcrypt',
'libuv',
'neovim',
'pixman',
  ],
  tap: [
	'amazeeio/lagoon-cli',
	'caskroom/cask',
	'homebrew/cask',
	'homebrew/cask-fonts',
	'homebrew/core',
	'homebrew/services',
	'sass/sass'
  ],
  cask: [
    //'adium',
    'agenda',
    'alfred',
    //'amazon-cloud-drive',
    //'atom',
    'appcleaner',
    'bettertouchtool',
    'coteditor',
    // 'box-sync',
    //'comicbooklover',
    'diffmerge',
    'docker', // docker for mac
    'dropbox',
    'feedly',
    'fork',
    'github',
    'evernote',
    'iterm2',
    'kitematic',
    'lastpass',
    'nvalt',
    'postman',
    'sequel-pro',
    'signal',
    //'macvim',
    'sizeup',
    'sketchup',
    'slack',
    'spotify',
    'the-unarchiver',
    //'torbrowser',
    //'transmission',
    'vimr',
    'visual-studio-code',
    'vlc',
    'xquartz',
    'font-fira-code',
    'macdown',
    'vagrant',
    'vagrant-manager',
    'virtualbox',
    'xact'
  ],
  gem: [
	  'bigdecimal',
	  'bourbon',
	  'bundler',
	  'CFPropertyList',
	  'cmath',
	  'colorize',
	  'csv',
	  'date',
	  'dbm',
	  'did_you_mean',
	  'e2mmap',
	  'etc',
	  'fcntl',
	  'fiddle',
	  'fileutils',
	  'forwardable',
	  'io-console',
	  'ipaddr',
	  'irb',
	  'json',
	  'libxml-ruby',
	  'logger',
	  'matrix',
	  'mini_portile2',
	  'minitest',
	  'msgpack',
	  'multi_json',
	  'mutex_m',
	  'neovim',
	  'net-telnet',
	  'nokogiri',
	  'openssl',
	  'ostruct',
	  'power_assert',
	  'prime',
	  'psych',
	  'ptools',
	  'pygmy',
	  'rake',
	  'rdoc',
	  'reline',
	  'rexml',
	  'rss',
	  'scanf',
	  'sdbm',
	  'shell',
	  'sqlite3',
	  'stringio',
	  'strscan',
	  'sync',
	  'test-unit',
	  'thor',
	  'thwait',
	  'tracer',
	  'webrick',
	  'xmlrpc',
	  'zlib'
  ],
  npm: [
    'antic',
    'buzzphrase',
    'cypress',
    'eslint',
    'instant-markdown-d',
    // 'generator-dockerize',
    'google-apps-script',
    'gulp',
    'npm-check-updates',
    'prettyjson',
    'trash',
    'vtop'
    // ,'yo'
  ],
  mas: [
    //com.apple.dt.Xcode (10.2.1)
    //'497799835',
    //com.if.Amphetamine (4.1.6)
    //'937984704',
    //net.shinyfrog.bear (1.6.15)
    //'1091189122',
    //com.monosnap.monosnap (3.5.8)
    //'540348655',
    //com.app77.pwsafemac (4.17)
    //'520993579',
  ],
  wget: [
	  'https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=osx&lang=en-US',
	  'https://www.google.com/chrome/browser/canary.html?platform=mac'
  ],

};
